config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  devise_for :users
  root to: "recipes#index"
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data =[
    {id: 0 , name: '---'},
    {id: 1 , name: 'すし・魚料理'},
    {id: 2 , name: '丼もの・揚げ物'},
    {id: 3 , name: 'ラーメン・麺類'},
    {id: 4 , name: '中華'},
    {id: 5 , name: '焼きもの・粉もの'},
    {id: 6 , name: '洋食・西洋料理'},
    {id: 7 , name: 'イタリアン'},
    {id: 8 , name: 'フレンチ'},
    {id: 9 , name: 'アジア・エスニック'},
    {id: 10 , name: 'お菓子・スイーツ'}
  ]

  include ActiveHash::Associations 
  has_many :recipes
end

app/models/categoty.rb
class Category < ActiveHash::Base
  self.data =[
    {id: 0 , name: '---'},
    {id: 1 , name: 'すし・魚料理'},
    {id: 2 , name: '丼もの・揚げ物'},
    {id: 3 , name: 'ラーメン・麺類'},
    {id: 4 , name: '中華'},
    {id: 5 , name: '焼きもの・粉もの'},
    {id: 6 , name: '洋食・西洋料理'},
    {id: 7 , name: 'イタリアン'},
    {id: 8 , name: 'フレンチ'},
    {id: 9 , name: 'アジア・エスニック'},
    {id: 10 , name: 'お菓子・スイーツ'}
  ]

  include ActiveHash::Associations 
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  belongs_to :time_required
  has_many_attached :images

  validates :title, presence: true
  validates :text, presence: true
  validates :category_id, numericality: { other_than: 0 }
  validates :time_required_id, numericality: { other_than: 0 }
  validate :image_length

  private

  def image_length
    if images.length >= 4
      errors.add(:images, "は3枚以内にしてください")
    end
  end
  
end

app/models/time_required.rb
class TimeRequired < ActiveHash::Base
  self.data =[
    {id: 0 , name: '---'},
    {id: 1 , name: '10分以内'},
    {id: 2 , name: '10分〜20分'},
    {id: 3 , name: '20分〜30分'},
    {id: 4 , name: '30分〜45分'},
    {id: 5 , name: '45分〜60分'},
    {id: 6 , name: '60分以上'}
  ]

  include ActiveHash::Associations 
  has_many :recipes
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :text, :category_id, :time_required_id, images: []).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to "Recipe-site", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "投稿する", new_recipe_path, class: "nav-link" %>
          </div>
        </div>
      </div>
      <div class="d-flex">
        <% if user_signed_in? %>
          <%= link_to "ログアウト", destroy_user_session_path(current_user), method: :delete, class: "btn btn-success btn-sm header-btn" %>
        <% else %>
          <%= link_to '新規登録', new_user_registration_path, class: "btn btn-success btn-sm header-btn" %>
          <%= link_to 'ログイン', new_user_session_path, class: "btn btn-success btn-sm header-btn" %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<%= link_to "投稿する", new_recipe_path %>

<div class="recipes-index">
  <% @recipes.each do |recipe| %>
    <div class="recipe-contents d-flex">
      <% if recipe.images.present? %>
        <%= image_tag recipe.images[0], class: "index-img" %>
      <% else %>  
        <%= image_tag "no_image.png", class: "index-img" %>
      <% end %>
      <div class="recipe">
        <div class="recipe-title">
          <%= link_to recipe.title, recipe_path(recipe) %>
        </div>
        <div class="recipe-content">
          カテゴリー: <span class="recipe-category"><%= recipe.category.name %></span>
          所要時間: <span class="recipe-time"><%= recipe.time_required.name %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="recipe-form ">
  <h1 class="text-center">レシピを投稿する</h1>

  <%= form_with model: @recipe, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <label class="text-secondary">料理名</label><br>
      <%= f.text_field :title, class: "form-control"%>
    </div>

    <div class="form-group">
      <label class="text-secondary">画像 (3枚まで)</label><br>
      <%= f.file_field :images, name: 'recipe[images][]', id: 'recipe-images' %>
    </div>

    <div id="new-image"></div>

    <div class="form-group">
      <label class="text-secondary">カテゴリー</label><br>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category"}) %>
    </div>

    <div class="form-group">
      <label class="text-secondary">所要時間</label><br>
      <%= f.collection_select(:time_required_id, TimeRequired.all, :id, :name, {}, {class:"time"}) %>
    </div>

    <div class="form-group">
      <label class="text-secondary">作り方</label><br>
      <%= f.text_area :text, class: "form-control", id: "recipe-area" %>
    </div>
    
    <div class="actions">
      <%= f.submit "投稿", class: "btn btn-primary de-btn" %>
    </div>
  <% end %>
</div>